const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM,VirtualConsole}=require('jsdom');const {webcrypto}=require('node:crypto');
const root=path.resolve(__dirname,'../dist'),flush=()=>new Promise(r=>setImmediate(r)),DEVICE='a'.repeat(32)+'.'+'b'.repeat(43),SHARE='c'.repeat(43),config={enabled:true,admin:{clientId:'admin-client',loginOrigin:'https://login.example.com',redirectUri:'https://pokemon.pir.kr/admin'}};
async function gate({pathname='/',key=null,responses={}}={}){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://pokemon.pir.kr'+pathname,runScripts:'outside-only',virtualConsole:new VirtualConsole()}),w=dom.window,calls=[];
 if(key)w.localStorage.setItem('pokemon-party-device-key',key);
 w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 const append=w.document.head.appendChild.bind(w.document.head);w.document.head.appendChild=node=>{const result=append(node);if(node.tagName==='LINK'&&node.rel==='stylesheet')setImmediate(()=>node.onload());return result;};
 w.fetch=async(url,options={})=>{calls.push({url,options});if(responses[url] instanceof Error)throw responses[url];if(url==='/game.html')return {ok:true,text:async()=>fs.readFileSync(path.join(root,'game.html'),'utf8')};const data=responses[url]|| (url==='/api/access/config'?config:{valid:true,deviceKey:DEVICE});return {ok:!data.reason,json:async()=>data};};
 w.eval(fs.readFileSync(path.join(root,'public/access.js'),'utf8'));for(let i=0;i<5;i++)await flush();
 return {w,calls,$:s=>w.document.querySelector(s),close:()=>dom.window.close()};
}
test('an uninvited browser sees only the envelope and never fetches the private game',async t=>{const h=await gate();t.after(h.close);assert.equal(h.$('h1').textContent,'파티 초대장이 필요합니다');assert.ok(h.$('img').src.endsWith('/public/envelope.svg'));assert.deepEqual(h.calls.map(r=>r.url),['/api/access/config']);assert.equal(h.w.PokemonAccess.valid,false);});
test('a valid saved device key is checked before game loading and sent with rankings',async t=>{const h=await gate({key:DEVICE});t.after(h.close);assert.deepEqual(h.calls.map(r=>r.url),['/api/access/config','/api/access/validate','/game.html']);assert.equal(JSON.parse(h.calls[1].options.body).deviceKey,DEVICE);assert.equal(h.w.PokemonAccess.headers()['x-device-key'],DEVICE);assert.equal(h.w.PokemonAccess.valid,true);assert.ok(h.$('#app'));assert.ok(h.w.document.head.querySelector('script[src="app.js"]'));});
test('a new invitation persists the issued device key before redirecting and does not load a quiz in the share URL',async t=>{const h=await gate({pathname:'/'+SHARE});t.after(h.close);assert.deepEqual(h.calls.map(r=>r.url),['/api/access/config','/api/access/claim']);assert.equal(h.w.localStorage.getItem('pokemon-party-device-key'),DEVICE);assert.equal(JSON.parse(h.calls[1].options.body).shareKey,SHARE);});
test('an existing device bypasses invitation issuance even when entering an expired invitation',async t=>{const h=await gate({pathname:'/'+SHARE,key:DEVICE});t.after(h.close);assert.deepEqual(h.calls.map(r=>r.url),['/api/access/config','/api/access/validate']);assert.equal(JSON.parse(h.calls[1].options.body).recordVisit,false);});
test('a blocked device is removed from browser storage and does not claim a new invitation',async t=>{const h=await gate({pathname:'/'+SHARE,key:DEVICE,responses:{'/api/access/validate':{reason:'invalid_device'}}});t.after(h.close);assert.equal(h.w.localStorage.getItem('pokemon-party-device-key'),null);assert.equal(h.w.PokemonAccess.valid,false);assert.equal(h.$('h1').textContent,'파티 초대장이 필요합니다');assert.ok(!h.calls.some(c=>c.url==='/api/access/claim'));});
test('temporary validation network errors preserve the permanent device key and offer retry',async t=>{const h=await gate({key:DEVICE,responses:{'/api/access/validate':Error('연결을 확인해 주세요')}});t.after(h.close);assert.equal(h.w.localStorage.getItem('pokemon-party-device-key'),DEVICE);assert.equal(h.$('#gate-retry').hidden,false);assert.ok(!h.calls.some(c=>c.url==='/game.html'));});
test('revocation on a loaded game closes dialogs, stops the game and restores the envelope',async t=>{const h=await gate({key:DEVICE});t.after(h.close);let stopped=false;h.w.addEventListener('pokemon-access-revoked',()=>stopped=true);h.w.PokemonAccess.revoked();await flush();assert.equal(stopped,true);assert.equal(h.w.localStorage.getItem('pokemon-party-device-key'),null);assert.equal(h.$('#app'),null);assert.equal(h.$('h1').textContent,'파티 초대장이 필요합니다');assert.ok(h.calls.some(c=>c.url==='/api/access/logout'));});
async function admin({session=null,pending=null,query='',data={}}={}){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'admin.html'),'utf8'),{url:'https://pokemon.pir.kr/admin'+query,runScripts:'outside-only',virtualConsole:new VirtualConsole()}),w=dom.window,calls=[];
 if(session)w.sessionStorage.setItem('pokemon-party-admin-session',JSON.stringify(session));if(pending)w.sessionStorage.setItem('pokemon-party-admin-login',JSON.stringify(pending));
 Object.defineProperty(w.crypto,'subtle',{value:webcrypto.subtle});w.TextEncoder=TextEncoder;w.confirm=()=>true;
 w.fetch=async(url,options={})=>{calls.push({url:String(url),options});const payload=String(url)==='/api/access/config'?config:String(url).includes('/oauth2/token')?{access_token:'access',refresh_token:'refresh',expires_in:1800}:data[String(url)]||{items:[],nextCursor:null};return {ok:true,status:200,json:async()=>payload};};
 w.eval(fs.readFileSync(path.join(root,'public/admin.js'),'utf8'));for(let i=0;i<5;i++)await flush();return {w,calls,$:s=>w.document.querySelector(s),close:()=>dom.window.close()};
}
test('public administrator shell requires login before reading device records',async t=>{const h=await admin();t.after(h.close);assert.ok(h.$('#admin-login'));assert.deepEqual(h.calls.map(c=>c.url),['/api/access/config']);h.$('#admin-login').click();for(let i=0;i<5;i++)await flush();const pending=JSON.parse(h.w.sessionStorage.getItem('pokemon-party-admin-login'));assert.ok(pending.state.length>=43&&pending.verifier.length>=43);assert.ok(!h.w.localStorage.getItem('pokemon-party-admin-session'));});
test('an OAuth callback with wrong state never exchanges a token or fetches admin records',async t=>{const h=await admin({pending:{state:'expected',verifier:'proof',created:Date.now()},query:'?code=code&state=wrong'});t.after(h.close);assert.deepEqual(h.calls.map(c=>c.url),['/api/access/config']);assert.ok(h.$('#admin-login'));assert.ok(h.$('#admin-login-note').textContent.includes('다시 로그인'));});
test('a valid PKCE callback exchanges the verifier and keeps admin tokens in session storage',async t=>{const h=await admin({pending:{state:'expected',verifier:'proof',created:Date.now()},query:'?code=code&state=expected'});t.after(h.close);const exchange=h.calls.find(c=>c.url.includes('/oauth2/token'));assert.equal(new URLSearchParams(exchange.options.body).get('code_verifier'),'proof');assert.equal(h.calls.find(c=>c.url==='/api/admin/devices').options.headers.authorization,'Bearer access');assert.ok(h.w.sessionStorage.getItem('pokemon-party-admin-session'));assert.equal(h.w.location.pathname,'/admin');assert.equal(h.w.location.search,'');});
test('administrator safely renders names and supports issuing links and blocking devices',async t=>{const id='a'.repeat(32),row={deviceId:id,trainerName:'<img src=x onerror=alert(1)>',createdAt:'2026-10-08T00:00:00Z',lastSeenAt:'2026-10-08T01:00:00Z',userAgent:'iPhone Safari',visitCount:2,status:'active'};const h=await admin({session:{access:'access',expires:Date.now()+1800000},data:{'/api/admin/devices':{items:[row]},'/api/admin/shares':{share:{url:'https://pokemon.pir.kr/'+SHARE},items:[]}}});t.after(h.close);assert.ok(h.$('.admin-row h3').textContent.includes('<img'));assert.equal(h.$('.admin-row img'),null);h.$('[data-device-state]').click();await flush();const block=h.calls.find(c=>c.options.method==='PATCH');assert.equal(block.url,'/api/admin/devices/'+id);assert.equal(JSON.parse(block.options.body).action,'block');h.$('#share-label').value='친구';h.$('#share-create').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));for(let i=0;i<5;i++)await flush();assert.equal(h.$('#new-share-url').value,'https://pokemon.pir.kr/'+SHARE);assert.ok(h.calls.some(c=>c.options.method==='POST'&&JSON.parse(c.options.body).label==='친구'));});
